export const FEEDBACK_FORM_REQUEST = "FEEDBACK_FORM_REQUEST";
export const FEEDBACK_FORM_SUCCESS = "FEEDBACK_FORM_SUCCESS";
export const FEEDBACK_FORM_FAIL = "FEEDBACK_FORM_FAIL";
export const FEEDBACK_FORM_RESET  = "FEEDBACK_FORM_RESET";