export const REGISTER_FORM_REQUEST = "REGISTER_FORM_REQUEST";
export const REGISTER_FORM_SUCCESS = "REGISTER_FORM_SUCCESS";
export const REGISTER_FORM_FAIL = "USER_CHECK_FAIL";
export const REGISTER_FORM_RESET  = "USER_CHECK_RESET";