export const REGISTER_FORM_REQUEST = "REGISTER_FORM_REQUEST";
export const REGISTER_FORM_SUCCESS = "REGISTER_FORM_SUCCESS";
export const REGISTER_FORM_FAIL = "REGISTER_FORM_FAIL";
export const REGISTER_FORM_RESET  = "REGISTER_FORM_RESET";